name: Publish

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 18.x

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  publish:
    runs-on: ubuntu-latest
    environment: production
    needs:
      - ci
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Check for existing version
        id: check-publish-version
        uses: tehpsalmist/npm-publish-status-action@v1
      - name: Publish
        if: ${{ steps.check-publish-version.outputs.exists == '0' }}
        run: |
          npm ci --prefer-offline
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish --access=public
      - name: Report existing version
        if: ${{ steps.check-publish-version.outputs.exists == '1' }}
        run: 'echo "Version already exists in npm registry"'
